name: Lint

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install luacheck and luarocks
        run: sudo apt-get install lua-check luarocks
      - name: Install luaunit
        run: sudo luarocks install luaunit
      - name: Lint
        run: luacheck .
      - name: Test
        run: lua5.1 Tests/Test.lua
